= ASAPP Coding Challenge - Chat

Coding challenge for ASAPP made with Springboot.

Decisions taken:

- Move out of Spark as it is not updated since Nov 18, 2020 (https://github.com/perwendel/spark)
- Use Springboot instead as it is a widely used framework easily to maintain, with the latest security updates, and out of the box features like pooling, dependency injection, etc.
- Use Maven instead of Gradle. As I was starting the project from scratch I prefer to use maven that I am more familiar with, so I don't have to waste time dealing with gradle now.
- Save the Message Content as metadata in a VARCHAR column as a JsonString. This way I can add new kind of messages without having to change anything in the database and keep the model simple enough for the use case. I would prefer using a PostgreSQL database and use a JSONB column for this instead of SQLite, but I think I already changed too many things from the original request, so I tried to make it work with SQLite.
- Keep AuthTokens in the same DB and don't use a Redis for this. I know is way better/faster use a redis to persist the tokens but considering the effort and the time given I choose to keep the tokens in the same DB in a new table to avoid the implementation cost of a Redis. (Keep it simple)
- Considered using a Signed JWT for the auth token so i could avoid persist it but that takes out the possibility of a logout and token invalidation (not implemented yet).

== Build And Run

Build jar with Maven wrapper

 ./mvn clean package

Build image with docker

 docker build -t app .

Run in docker

 docker run -p 8080:8080 app

=== Deploy in k8s

This will create a SQLite database pod to simulate the DB. You can always comment that from the manifest and configure a different database URL in the Chat ConfigMap.

1st You need to manually create the configmap with `schema.sql` to init the database created in a pod.

 kubectl create configmap schema --from-file=./src/test/resources/schema.sql

Then deploy the manifest

 kubectl apply -f ./k8s/deployment.yaml

port forward to the service

 kubectl port-forward svc/chat 8080:80

Then curl into it

 curl -X POST 'localhost:8080/check'
 {"health":"OK"}%
