spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: 'sa'
    password: 'password'
    driverClassName: org.h2.Driver
#    url: 'jdbc:sqlite:/Users/msingermann/Downloads/sqlite-tools-osx-x86-3380300/test.db'
#    username: ''
#    password: ''
    hikari:
      auto-commit: false
#      maximum-pool-size: 1
#      max-lifetime: 0
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        dialect: org.sqlite.hibernate.dialect.SQLiteDialect
#hibernate:
#  dialect: org.sqlite.hibernate.dialect.SQLiteDialect
server:
  error:
    include-message: always


# CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, name varchar(255) NOT NULL UNIQUE, password varchar(255) NOT NULL);
#add an index on name (on id should be created automatically right?)