# This are not the actual secrets and user but i leave the config, so it can be added if needed later.
apiVersion: v1
kind: Secret
metadata:
  name: chat-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
data:
  DATABASE_URL: "jdbc:postgresql://postgres.default.svc:5432/postgres"
#  DATABASE_URL: "jdbc:sqlite:memory:chat.db"
  POSTGRES_USERNAME: "postgres"
  POSTGRES_DATABASE: "postgres"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          imagePullPolicy: Never
          image: postgres:14.2
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: chat-secrets
            - configMapRef:
                name: chat-config

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  labels:
    app: chat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          imagePullPolicy: Never
          image: chat:1.0.0
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: chat-secrets
            - configMapRef:
                name: chat-config

---

apiVersion: v1
kind: Service
metadata:
  name: chat
spec:
  type: LoadBalancer
  selector:
    app: chat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
